[package]
name = "rust-decryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
gtk = "0.16.2"
openssl = "0.10.45"
anyhow = "*"
